### ISSUE TITLE
Add api_endpoint

### ISSUE THREAD

**Issue by jeromegn** [moomerman/twitter_oauth#10]
Hello,

I'm really interested in using Apigee for my application. It requires that you use a proxy to connect to the twitter api. I tried modifying the gem to use the Apigee api instead, but my limited knowledge wasn't up to the task!

The "twitter" gem already has implemented it, but I prefer the simplicity of this gem :) So I'll keep using it even though the api_endpoint feature isn't implemented. This is an enhancement request.

**Comment by moomerman** [comment]
Thanks for the request. I will add it this weekend and let you know.

**Comment by moomerman** [comment]
I've just pushed version 0.4.1 with api endpont support.  You can specify it when creating the client TwitterOAuth::Client.new(:api_endpoint => 'http://api.apigee.com/twitter', ...)

**Comment by moomerman** [comment]
Hi, sorry hadn't tested it properly before.  I have just pushed v0.4.2 - this uses a different syntax:

TwitterOAuth::Client.new(:proxy => 'http://twitter.username.apigee.com', ...)

You need to obtain the request token though without the proxy, once you have the token you can create a client with the proxy and the token and everything works.

**Comment by jeromegn** [comment]
That was quick. Thank you so much!

**Comment by jeromegn** [comment]
I used this and it seems to work, though I had to thoroughly delete the session cookies:
    before do
      @user = session[:user]
      if @user
        @client = TwitterOAuth::Client.new(
          :consumer_key => ENV['CONSUMER_KEY'] || @@config['consumer_key'],
          :consumer_secret => ENV['CONSUMER_SECRET'] || @@config['consumer_secret'],
          :token => session[:access_token],
          :secret => session[:secret_token],
          :proxy => "my_apigee_url"
        )
      else
        @client = TwitterOAuth::Client.new(
          :consumer_key => ENV['CONSUMER_KEY'] || @@config['consumer_key'],
          :consumer_secret => ENV['CONSUMER_SECRET'] || @@config['consumer_secret']
        )
      end
    end
