### ISSUE TITLE
How to use as command line with PIN?

### ISSUE THREAD

**Issue by simonszu** [moomerman/twitter_oauth#27]
It seems that i can't understand the Readme correctly, but i think the Readme only handles web based access.

I want to use twitter_oauth in a command line app. I can authorize with twitter, but when i have the PIN, i don't know how to use it.
Can you include these steps in your Readme as well, please? Thank you.

**Comment by PatParslow** [comment]
Where the readme says:
access_token = client.authorize(
  request_token.token,
  request_token.secret,
  :oauth_verifier => params[:oauth_verifier]
)

put your PIN in place of params[:oauth_verifier] e.g.
:oauth_verifier => "PIN pasted from site"

(obviously for an actual app, you will have the PIN in a variable, but this works for testing)

**Comment by moomerman** [comment]
Added documentation for the PIN-based flow.
