### ISSUE TITLE
error using twitter_oauth  401:unauthorized ?

### ISSUE THREAD

**Issue by bournenapster** [moomerman/twitter_oauth#32]
i have done a simple code  and configured callback url correctly in twitter app as well as defined it here but why it is unauthorized ?:
class TwitterController < ApplicationController
  def index
  end

  def login
oauth_confirm_url = "http://127.0.0.1:3000/twitter/finalize"
@client = TwitterOAuth::Client.new(
    :consumer_key => '6J4wc5nK1Yz8EKj0GQ3SFg',
    :consumer_secret => 'U0Xh7hs92ObFYxA0Vh3GkJQRl1csq7ptmGjMI5WSg'
)

@request_token = @client.request_token(:oauth_callback => oauth_confirm_url)
redirect_to @request_token.authorize_url

@access_token = @client.authorize(
    @request_token.token,
    @request_token.secret,
  :oauth_verifier => params[:oauth_verifier]
)
  end

  def finalize
  end

but i am still gewtting 401 : unauthorized ?
if i put the code as======> i.e i put the access_token code in twitter/finalize it says 
=======================================--------------------------------------------------------------------------------------------------------

NoMethodError in TwitterController#finalize

undefined method `token' for nil:NilClass

Rails.root: /home/bourne/Documents/sandy/try0
Application Trace | Framework Trace | Full Trace

app/controllers/twitter_controller.rb:22:in `finalize'

Request

Parameters:

{"oauth_token"=>"FClwPxCcYyrKfkVsfrS2mdXF1bl8MqOMSqUa1APNc",
 "oauth_verifier"=>"AF797f6H5EGvjf1xVfxXCZJgWBGezIorL6K4D4qk8"}

=========================================-------------------------------------------------------------------------------------------------------  
def finalize

@access_token = @client.authorize(
    @request_token.token,
    @request_token.secret,
  :oauth_verifier => params[:oauth_verifier]
)
end

**Comment by ptuchster** [comment]
the last version of finalize action is right. Just you need to create new client. This is first. Second- you trying to get token and secret keys from @request_token, but in finalize action it's realy clean. What you need this is to store request token keys (token and secret) from ligon action i.e. to session.
def login
...
#after getting request token but before redirect
session[:token]=@request_token.token
session[:secret]= @request_token.secret
...
end

def finalize

# firstly you need to create client

client = TwitterOAuth::Client.new(
:consumer_key => '6J4wc5nK1Yz8EKj0GQ3SFg',
:consumer_secret => 'U0Xh7hs92ObFYxA0Vh3GkJQRl1csq7ptmGjMI5WSg'
)
access_token = client.authorize(
session[:token],
session[:secret],
:oauth_verifier => params[:oauth_verifier]
)
end

in accesstoken you will get token and secret to future authentication of user without verification by redirecting to twitter. So you need to store it if you want.

**Comment by leonelgalan** [comment]
I'm having the same error (401) and it is in this line:

``` ruby
@request_token = @client.request_token(:oauth_callback => oauth_confirm_url)
```

So what's on finalize or what's stored in session doesn't matter for this particular error.

**Comment by leonelgalan** [comment]
This worked for me, no more **401**

On dev.twitter.com don't leave 'Callback URL:' empty. Your app will be considered a Desktop app and the response you get, along with the 401 HTTP code says:

``` xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>
```
