### ISSUE TITLE
Cannot makes status updates.

### ISSUE THREAD

**Issue by SteveAquino** [moomerman/twitter_oauth#35]
When calling client.status("Hello World!"), or anything else, I get the following error:

JSON::ParserError: 757: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

Looking at the console i can see the response body, contained within are the following errors:

413 Request Entity Too Large: The requested resource/1/statuses/update.json does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

Request Entity Too Large: your browser sent a request that this server could not understand.

I've tried issuing manual CURL commands and it posts just fine, but I can't for the life of me figure out what the problem is.  Following the error trace, it looks like the gem is calling get instead of post, but even manually calling send("post", url, status: "Hello World!") returns errors (albeit a different one).

I've been pulling my hair out for hours trying to figure this one out, I never had this problem before (been testing all month) until today.  Please help!

**Comment by lothar59** [comment]
JSON::ParserError: 757: unexpected token at '<!DOCTYPE html>

Same error. Did you find the solution since ?

**Comment by SteveAquino** [comment]
Honestly no, I was forced to use this gem for authentication and then use `twitter` gem for actual API calls.  Was unable to get full functionality from either gem individually.

The twitter gem I used is here https://github.com/jnunemaker/twitter, it's more active and maybe you'll have some luck.

**Comment by SteveAquino** [comment]
Also just noticed theres a ton of old pull requests, so I don't think anyone is maintaining this gem anymore.

**Comment by lothar59** [comment]
Thanks for your reply. In fact I wasn't using this gem but I had the same issue with the parser. I figured out the problem playing with the json response in the console.

**Comment by danielduhh** [comment]
Im getting this issue too. Im trying to use OAuth with the uservoice API.. How did you fix this?

**Comment by jonathan-rodan** [comment]
This might help http://jrgns.net/content/twitter_api_request_entity_too_large_http_413_error/
