### ISSUE TITLE
Not working for twitter login anymore because of Twitter drop api 1.0 .

### ISSUE THREAD

**Issue by peeyushsingla** [moomerman/twitter_oauth#51]
I was working on an application that is having rails 3.0.10 and ruby 1.9 it is using twitter_oauth for signup with twitter in my application I have checked out that twitter drop support for api 1.0 and for this gem we are using this.

**Comment by moomerman** [comment]
Hi, have you tried the latest version?  there have been some updates to support the new api.

**Comment by peeyushsingla** [comment]
Hey, Which one is latest version and how can I install that using my gemfile?

**Comment by moomerman** [comment]
$ gem list -r twitter_oauth

**\* REMOTE GEMS ***

twitter_oauth (0.4.94)

**Comment by peeyushsingla** [comment]
Let me try

**Comment by peeyushsingla** [comment]
Its also not working for that still showing same error :(

**Comment by moomerman** [comment]
Can you show me a simple example of how you're using it and the error you're encountering?

**Comment by peeyushsingla** [comment]
Hey thanx for your help it starts working after up gradation here was some issue with my code.

**Comment by HenleyChiu** [comment]
Still doesn't work.

It works when I do:
consumer = OAuth::Consumer.new(consumer_key, 
                               consumer_secret,
                               :site => 'https://api.twitter.com',
                               :authorize_path => '/oauth/authenticate',
                               :sign_in => true)

# get the request_token and pass my callback url

request_token = consumer.get_request_token({:oauth_callback => callback_url})
