### ISSUE TITLE
Need account/update_profile added to account.rb

### ISSUE THREAD

**Issue by jaredbrown** [moomerman/twitter_oauth#6]
account.rb is missing account/update_profile

http://dev.twitter.com/doc/post/account/update_profile

This issue is a request to implement account/update_profile in account.rb

**Comment by bgreenlee** [comment]
I've added it to my fork over at http://github.com/bgreenlee/twitter_oauth

**Comment by moomerman** [comment]
New version twitter_oauth-0.3.4 available with update_profile
