### ISSUE TITLE
what's wrong with json 1.4.3?

### ISSUE THREAD

**Issue by agibralter** [moomerman/twitter_oauth#7]

**Comment by agibralter** [comment]
Would you mind pushing http://github.com/moomerman/twitter_oauth/commit/5c68f16aca8f30bf66d5e4283062f41b4b4fd823 to rubygems?

Thanks!

**Comment by moomerman** [comment]
Should now be in the latest gem

**Comment by agibralter** [comment]
Awesome! Thank you!
